import { ExternalProduct, Product } from "./types";

const SEARCH_URL = "https://world.openfoodfacts.org/cgi/search.pl";

async function fetchWithTimeoutAndRetry(url: string, retries = 2, delayMs = 1000, timeoutMs = 8000) {
  for (let i = 0; i <= retries; i++) {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), timeoutMs);

    try {
      const response = await fetch(url, {
        headers: {
          "User-Agent": "ElexirApp/1.0 (contact@elexir.com)",
          "Accept": "application/json"
        },
        signal: controller.signal
      });

      clearTimeout(timeoutId);

      if (!response.ok) {
        throw new Error(`HTTP error: ${response.status}`);
      }

      return await response.json();
    } catch (error) {
      clearTimeout(timeoutId);
      if (i === retries) {
        throw error;
      }
      // Wait before retrying
      await new Promise(res => setTimeout(res, delayMs));
    }
  }
}

export async function searchOpenFoodFacts(query: string): Promise<{ products: Product[], error: boolean }> {
  try {
    const fields = "code,product_name,brands,image_url,categories_tags,nutriments,ingredients_text";
    const url = `${SEARCH_URL}?search_terms=${encodeURIComponent(query)}&search_simple=1&action=process&json=1&page_size=20&fields=${fields}`;
    
    const data = await fetchWithTimeoutAndRetry(url);
    const products: ExternalProduct[] = data.products || [];

    return { products: products.map(normalizeExternalProduct), error: false };
  } catch (error) {
    console.warn("Warning: Could not fetch from Open Food Facts:", error);
    return { products: [], error: true };
  }
}

import { inferProductGoals } from "./matching";

function normalizeExternalProduct(extProduct: ExternalProduct): Product {
  const p: Product = {
    id: "", // Will be generated by Supabase when inserted
    external_id: extProduct.code || null,
    barcode: extProduct.code || null,
    name: extProduct.product_name || null,
    brand: extProduct.brands || null,
    image_url: extProduct.image_url || null,
    category: extProduct.categories_tags ? extProduct.categories_tags.join(", ") : null,
    source: "open_food_facts",
    raw_data: extProduct,
    created_at: new Date().toISOString(),
  };

  p.inferred_goals = inferProductGoals(p);
  return p;
}
